### ISSUE TITLE
A private repo behind a "git+https" URL can not be installed

### ISSUE THREAD

**Issue by kahara** [ByteInternet/pip-install-privates#19]
The assumption that a repo behind a `git+https` URL never refers to a private one leads to an issue when it does.

Fixing this by tweaking the URLs may not always be possible as the end user may be required to install dependencies from a `requirements.txt` file not under the end user's direct control, containing (private) `git+https` repos.

**Comment by kerrermanisNL** [comment]
@kahara to help me understand the issue a little better, could you provide such a URL?

**Comment by kahara** [comment]
Like this in `requirements.txt`:

```
-e git+https://github.com/kahara/testrepo.git#egg=xxx
```

**Comment by kerrermanisNL** [comment]
@kahara I think this issue should be fixed in https://github.com/ByteInternet/pip-install-privates/pull/23
