### ISSUE TITLE
Release to Pypi

### ISSUE THREAD

**Issue by AdrieanKhisbe** [ByteInternet/pip-install-privates#5]
Is it possible to release `pip-install-privates` to pypi s we can just install it with `pip install pip-install-privates`

(I found a guide about how to do that: http://peterdowns.com/posts/first-time-with-pypi.html)

**Comment by vdloo** [comment]
Good idea, but the current repo probably requires some changes before we can do so. For example the package name in the setup.py is not the same as the name, and there currently isn't a setup.cfg.

**Comment by AdrieanKhisbe** [comment]
if you point me which I could take Care of those. :)

**Comment by vdloo** [comment]
I'll try to make a release and put it on pypi on monday 

pypi preparations https://github.com/ByteInternet/pip-install-privates/pull/7

**Comment by AdrieanKhisbe** [comment]
great! 😃

**Comment by vdloo** [comment]
this package is now on pypi: https://pypi.python.org/pypi/pip_install_privates

**Comment by AdrieanKhisbe** [comment]
@vdloo awesome!
though you could have keep the command name `pip-install-privates` with dash rather than underscores
